/*
 * Jakefile
 * Aristo2
 *
 * Created by You on June 12, 2011.
 * Copyright 2011, Your Company All rights reserved.
 */

var ENV = require("system").env,
    FILE = require("file"),
    task = require("jake").task,
    FileList = require("jake").FileList,
    blend = require("cappuccino/jake").blend,
    configuration = ENV["CONFIG"] || ENV["CONFIGURATION"] || ENV["c"] || "Debug";


blend ("Aristo2.blend", function(Aristo2Task)
{
    Aristo2Task.setBuildIntermediatesPath(FILE.join("Build", "Aristo2.build", configuration))
    Aristo2Task.setBuildPath(FILE.join("Build", configuration));

    Aristo2Task.setThemeDescriptors(new FileList("ThemeDescriptors.j"));
    Aristo2Task.setIdentifier("com.280n.com.yourcompany.Aristo2");
    Aristo2Task.setResources(new FileList("Resources/*"));
});

task ("default", ["Aristo2.blend"]);

task ("build", ["default"]);

